## Autoload owning every sound the game makes (Part 25).
##
## Callers say what happened, not how loud it should be:
## [code]Audio.play(&"chop")[/code]. The bus a sound goes to is decided here from
## its name, so the options screen only has to move three sliders.
##
## Effects come from [code]res://resources/audio/sfx[/code], generated by
## [code]tools/make_sfx.gd[/code]. A missing file is not an error — the game stays
## playable and silent for that one sound.
extends Node

## Buses declared in [code]resources/audio/default_bus_layout.tres[/code].
const BUS_MASTER := &"Master"
const BUS_MUSIC := &"Music"
const BUS_SFX := &"SFX"
const BUS_UI := &"UI"

const SFX_DIR := "res://resources/audio/sfx"
const SETTINGS_PATH := "user://settings.cfg"

## Enough voices that a chop, a pickup and a cluck can overlap without cutting
## each other off, but few enough to stay cheap.
const VOICES := 12

## Sounds routed to the UI bus rather than SFX, so menu noise can be turned down
## without muting the farm.
const UI_SOUNDS: Array[StringName] = [&"ui_click", &"ui_move", &"deny"]

var _streams: Dictionary[StringName, AudioStream] = {}
var _voices: Array[AudioStreamPlayer] = []
var _next_voice: int = 0
var _music: AudioStreamPlayer
var _music_track: StringName = &""

## Guards against a sound firing many times in the same frame — a rock breaking
## drops several items, and each pickup would otherwise stack into a click.
var _last_played: Dictionary[StringName, int] = {}


func _ready() -> void:
	_load_streams()
	_build_voices()
	_load_settings()


## Play a one-shot effect. [param pitch_spread] jitters the pitch a little so a
## repeated sound does not sound mechanical; pass 0.0 for UI clicks.
func play(sound: StringName, pitch_spread: float = 0.08, volume_db: float = 0.0) -> void:
	var stream: AudioStream = _streams.get(sound)
	if stream == null:
		return

	# One instance of a given sound per frame is plenty.
	var frame := Engine.get_process_frames()
	if _last_played.get(sound, -1) == frame:
		return
	_last_played[sound] = frame

	var player := _voices[_next_voice]
	_next_voice = (_next_voice + 1) % _voices.size()

	player.stream = stream
	player.bus = BUS_UI if sound in UI_SOUNDS else BUS_SFX
	player.pitch_scale = 1.0 if is_zero_approx(pitch_spread) else randf_range(
		1.0 - pitch_spread, 1.0 + pitch_spread
	)
	player.volume_db = volume_db
	player.play()


## Start a looping track, or do nothing if it is already the one playing.
func play_music(track: StringName, fade: float = 1.0) -> void:
	if track == _music_track and _music.playing:
		return

	var stream: AudioStream = _streams.get(track)
	_music_track = track
	if stream == null:
		_music.stop()
		return

	_music.stream = stream
	_music.volume_db = linear_to_db(0.001) if fade > 0.0 else 0.0
	_music.play()
	if fade > 0.0:
		create_tween().tween_property(_music, "volume_db", 0.0, fade)


func stop_music(fade: float = 0.6) -> void:
	_music_track = &""
	if not _music.playing:
		return
	if fade <= 0.0:
		_music.stop()
		return
	var tween := create_tween()
	tween.tween_property(_music, "volume_db", linear_to_db(0.001), fade)
	tween.tween_callback(_music.stop)


## 0.0 to 1.0, which is what a slider hands us. Muting is a volume of exactly 0.
func set_bus_volume(bus: StringName, linear: float) -> void:
	var index := AudioServer.get_bus_index(String(bus))
	if index < 0:
		return
	AudioServer.set_bus_mute(index, is_zero_approx(linear))
	AudioServer.set_bus_volume_db(index, linear_to_db(maxf(linear, 0.0001)))
	_save_settings()


func bus_volume(bus: StringName) -> float:
	var index := AudioServer.get_bus_index(String(bus))
	if index < 0:
		return 1.0
	if AudioServer.is_bus_mute(index):
		return 0.0
	return db_to_linear(AudioServer.get_bus_volume_db(index))


func has(sound: StringName) -> bool:
	return _streams.has(sound)


# --- setup -------------------------------------------------------------------


func _load_streams() -> void:
	var dir := DirAccess.open(SFX_DIR)
	if dir == null:
		push_warning("No sound effects found at %s — run tools/make_sfx.gd." % SFX_DIR)
		return

	for file in dir.get_files():
		# Exported projects see .remap; the editor sees the file itself.
		var clean := file.trim_suffix(".remap")
		if not clean.ends_with(".res"):
			continue
		var stream := ResourceLoader.load("%s/%s" % [SFX_DIR, clean]) as AudioStream
		if stream == null:
			continue
		if stream is AudioStreamWAV:
			# Effects are one-shots; a loop flag on a 0.2s file would be a bug.
			(stream as AudioStreamWAV).loop_mode = AudioStreamWAV.LOOP_DISABLED
		_streams[StringName(clean.get_basename())] = stream


func _build_voices() -> void:
	for index in VOICES:
		var player := AudioStreamPlayer.new()
		player.bus = BUS_SFX
		add_child(player)
		_voices.append(player)

	_music = AudioStreamPlayer.new()
	_music.bus = BUS_MUSIC
	add_child(_music)


func _load_settings() -> void:
	var config := ConfigFile.new()
	if config.load(SETTINGS_PATH) != OK:
		return
	for bus in [BUS_MASTER, BUS_MUSIC, BUS_SFX]:
		var stored: float = config.get_value("audio", String(bus), -1.0)
		if stored >= 0.0:
			var index := AudioServer.get_bus_index(String(bus))
			if index >= 0:
				AudioServer.set_bus_mute(index, is_zero_approx(stored))
				AudioServer.set_bus_volume_db(index, linear_to_db(maxf(stored, 0.0001)))


func _save_settings() -> void:
	var config := ConfigFile.new()
	config.load(SETTINGS_PATH)
	for bus in [BUS_MASTER, BUS_MUSIC, BUS_SFX]:
		config.set_value("audio", String(bus), bus_volume(bus))
	config.save(SETTINGS_PATH)
